### ISSUE TITLE
Unpin all files in library

### ISSUE THREAD

**Issue by DevonJames** [dloa/pinbotwizard#3]
Add an additional function to do the exact opposite that the script does right now - create a list of "all files" published to the library and then `ipfs pin rm` for each of them.

Note, this is not a "unpin everything the user currently has pinned" function, it should be specifically looking at the libraryd:media:all API endpoint for what IPFS files to unpin.

**Comment by gleim** [comment]
This should already exist.  Try: node dlaoAutopin.js | pinfilesrm

**Comment by DevonJames** [comment]
just saw that, checking that out now

**Comment by DevonJames** [comment]
Yup, gtg
