### ISSUE TITLE
Error Status 1 crashes

### ISSUE THREAD

**Issue by DevonJames** [dloa/pinbotwizard#4]
Each time i run the script it crashes when it gets to this IPFS hash

```pinned QmWnecqhL9z1WERXyvgjuGtNYHDRNq86cjqh5FXuhFH9ZL recursively

2016/04/20 12:07:00 exit status 1```

Note: running `pinfilesrm` also crashes when it gets to this hash. If i try to run it a second time at that point, it crashes right away. If i run `pinfiles` again, it will get to that hash and crash, and then i can run `pinfilesrm` and it will, again go thru a list of 15 hashes successfully and then crash at the same hash again.

**Comment by DevonJames** [comment]
Mac OSX 10.11
Libraryd v.102
IPFS v.0.3.9-dev

**Comment by gleim** [comment]
I'm not in a position to replicate this on my side, but perhaps the *repo gc* step just needs to be performed from https://github.com/ipfs/examples/tree/master/examples/pinning

https://github.com/ipfs/examples/tree/master/examples/pinning

**Comment by gleim** [comment]
I'm not in a position to replicate this on my side, but perhaps the *repo gc* step just needs to be performed from https://github.com/ipfs/examples/tree/master/examples/pinning

https://github.com/ipfs/examples/tree/master/examples/pinning

**Comment by gleim** [comment]
I'm not in a position to replicate this on my side, but perhaps the *repo gc* step just needs to be performed from https://github.com/ipfs/examples/tree/master/examples/pinning

https://github.com/ipfs/examples/tree/master/examples/pinning

**Comment by gleim** [comment]
I'm not in a position to replicate this on my side, but perhaps the *repo gc* step just needs to be performed from https://github.com/ipfs/examples/tree/master/examples/pinning

https://github.com/ipfs/examples/tree/master/examples/pinning

**Comment by gleim** [comment]
I'm not in a position to replicate this on my side, but perhaps the *repo gc* step just needs to be performed from https://github.com/ipfs/examples/tree/master/examples/pinning

https://github.com/ipfs/examples/tree/master/examples/pinning

**Comment by gleim** [comment]
I'm not in a position to replicate this on my side, but perhaps the *repo gc* step just needs to be performed from https://github.com/ipfs/examples/tree/master/examples/pinning

https://github.com/ipfs/examples/tree/master/examples/pinning

**Comment by gleim** [comment]
I'm not in a position to replicate this on my side, but perhaps the _repo gc_ step just needs to be performed from https://github.com/ipfs/examples/tree/master/examples/pinning

https://github.com/ipfs/examples/tree/master/examples/pinning

**Comment by gleim** [comment]
I'm not in a position to replicate this on my side, but perhaps the *repo gc* step just needs to be performed from https://github.com/ipfs/examples/tree/master/examples/pinning

https://github.com/ipfs/examples/tree/master/examples/pinning

**Comment by cchrysostom** [comment]
The problem was a poorly formated ipfs path. pinfiles now can handle this by skipping any problematic file while attempting to pin. [This commit](https://github.com/dloa/pinbotwizard/commit/cecd3d5d23088c6006c04266d6e1f76a7975402d) fixes this issue.
